baseURL = 'https://cuterwrite.top/image-hosting'
title = "Gallery"
languageCode = "en"
copyright = "© Cuterwrite"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "en"
enableRobotsTXT = true
timeZone = "Asia/Shanghai"
theme = "github.com/nicokaiser/hugo-theme-gallery/v2"
timeout = "300s"

[params]
  title = "My Gallery"
  description = "A gallery of my photos"
  defaultTheme = "dark"

[author]
  name = "Cuterwrite"

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 100
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.112.0"

[menu]
[[menu.footer]]
  name = "GitHub"
  url = "https://github.com/PKUcoldkeyboard/"
  weight = 3

